services:
  ai-search:
    image: ghcr.io/cedya77/stremio-ai-search:latest
    build: 
      context: https://github.com/itcon-pty-au/stremio-ai-search.git
      dockerfile: Dockerfile
    container_name: ai-search
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 7000 # needed when using community image
    expose:
      - 7000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-search.rule=Host(`${AI_SEARCH_HOSTNAME}`)"
      - "traefik.http.routers.ai-search.entrypoints=websecure"
      - "traefik.http.routers.ai-search.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ai-search.middlewares=authelia@docker"
      - "traefik.http.services.ai-search.loadbalancer.server.port=7000"

    profiles:
      - ai-search
      - stremio
      - all
