services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: $PUID:$PGID
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      # - ${DOCKER_DATA_DIR}/recyclarr:/config
      - ${DOCKER_DATA_DIR}/recyclarr/cache:/config/cache
      - ${DOCKER_DATA_DIR}/recyclarr/logs:/config/logs
      - ${DOCKER_DATA_DIR}/recyclarr/repositories:/config/repositories
      - ${DOCKER_DATA_DIR}/recyclarr/configs:/config/configs
      - ${DOCKER_DATA_DIR}/recyclarr/includes:/config/includes
      - ./recyclarr.yml:/config/recyclarr.yml
      - ./secrets.yml:/config/secrets.yml
    depends_on:
      - sonarr
      - sonarr4k
      - sonarranime
      - radarr
      - radarr4k
      - radarranime
    profiles:
      - all
      - recyclarr
      - debrid_media_server
