services:
  tmdb-addon:
    image: viren070/tmdb-addon:latest
    container_name: tmdb-addon
    restart: unless-stopped
    expose:
      - 3232
    environment:
      - PORT=3232
      - TMDB_API=${TMDB_API_KEY?}  # https://www.themoviedb.org/settings/api
      - FANART_API=${FANART_API_KEY?}  # https://fanart.tv/get-an-api-key/
      - HOST_NAME=https://${TMDB_ADDON_HOSTNAME?}
      - REDIS_URL=redis://tmdb-addon_redis:6379
      - METRICS_USER=${METRICS_USER?}
      - METRICS_PASSWORD=${METRICS_PASSWORD?}
      - META_TTL=604800  # 1 week
      - CATALOG_TTL=86400  # 1 day
      # - NO_CACHE=true  # uncomment to disable cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tmdb.rule=Host(`${TMDB_ADDON_HOSTNAME?}`)"
      - "traefik.http.routers.tmdb.entrypoints=websecure"
      - "traefik.http.routers.tmdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tmdb.middlewares=authelia@docker"
      - "traefik.http.services.tmdb.loadbalancer.server.port=3232"
    depends_on:
      tmdb-addon_redis:
        condition: service_healthy
    profiles:
      - tmdb-addon
      - all
  
  tmdb-addon_redis:
    image: redis:latest
    container_name: tmdb-addon_redis
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/tmdb-addon/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - tmdb-addon
      - all