services:
  anime-kitsu:
    image: charleeislegend/anime-kitsu:latest
    container_name: anime-kitsu
    expose:
      - 7000
    environment:
      - PORT=7000
      - ADDON_URL=https://${ANIME_KITSU_HOSTNAME}
      - FANART_APIKEY=${FANART_APIKEY}
      - META_TTL=86400
      - CATALOG_TTL=86400
      - CACHE_MAX_AGE=43200
      - REDIS_URL=redis://kitsu_redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anime-kitsu.rule=Host(`${ANIME_KITSU_HOSTNAME}`)"
      - "traefik.http.services.anime-kitsu.loadbalancer.server.port=7000"
      - "traefik.http.routers.anime-kitsu.entrypoints=websecure"
      - "traefik.http.routers.anime-kitsu.tls=true"
      - "traefik.http.routers.anime-kitsu.tls.certresolver=letsencrypt"
      - "traefik.http.routers.anime-kitsu.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/anime-kitsu/imdb_mapping.json:/home/node/app/static/data/imdb_mapping.json
    profiles:
      - anime-kitsu
      - stremio
      - all

  anime-kitsu_redis:
    image: redis:latest
    container_name: anime-kitsu_redis
    restart: unless-stopped
    volumes:
      - ./data/kitsu/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5 
    profiles:
      - anime-kitsu
      - stremio
      - all


