services:
  stremthru:
    image: muniftanjim/stremthru:latest
    container_name: stremthru
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      stremthru_redis:
        condition: service_healthy
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremthru.rule=Host(`${STREMTHRU_HOSTNAME?}`)"
      - "traefik.http.routers.stremthru.entrypoints=websecure"
      - "traefik.http.routers.stremthru.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stremthru.middlewares=authelia@docker"
      - "traefik.http.services.stremthru.loadbalancer.server.port=8080"
    profiles:
      - stremthru
      - stremio
      - all
  
  stremthru_redis:
    image: redis:latest
    container_name: stremthru_redis
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - stremthru
      - stremio
      - all

