services:
  stremthru:
    image: muniftanjim/stremthru:latest
    container_name: stremthru
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - STREMTHRU_HTTP_PROXY=http://warp:1080
      - STREMTHRU_TUNNEL=*:false,torrentio.strem.fun:true       # Only tunnel hostnames that block VPS access (e.g. Torrentio)
      - STREMTHRU_PROXY_AUTH=user1:pass1,user2:pass2
      - STREMTHRU_STORE_AUTH=*:realdebrid:abc...xyz             # Add apikey
      - STREMTHRU_STORE_TUNNEL=realdebrid:api                   # Only send RD API via tunnel, not all access (e.g playback)
      - STREMTHRU_STORE_CONTENT_PROXY=*:true,easydebrid:false,premiumize:false
      - STREMTHRU_DATABASE_URI=sqlite://./data/stremthru.db
      - STREMTHRU_REDIS_URI=redis://stremthru_redis:6379
    depends_on:
      stremthru_redis:
        condition: service_healthy
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremthru.rule=Host(`${STREMTHRU_HOSTNAME?}`)"
      - "traefik.http.routers.stremthru.entrypoints=websecure"
      - "traefik.http.routers.stremthru.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stremthru.middlewares=authelia@docker"
      - "traefik.http.services.stremthru.loadbalancer.server.port=8080"
    profiles:
      - stremthru
      - stremio
      - all
  
  stremthru_redis:
    image: redis:latest
    container_name: stremthru_redis
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - stremthru
      - stremio
      - all

